### PR TITLE
Add zsh shell auto-completion function

### PR DESCRIPTION
**Pull request by nevzatseferoglu**
This PR introduces a basic auto-completion function for zsh shell.
- Options/flags were extracted based on help page.
- The guide includes different ways of setup options.
- I believe, completions setup can be directly embedded to actual installation of the CLI [here](https://github.com/ddosify/ddosify/blob/master/scripts/install.sh).

Screen Shot 2023-02-05 at 03 54 58

### CODE REVIEW

**Comment by ddosifyadmin** [comment]
Max. Delta Time op: 2.39 / 15
Max. Delta Alloc op: 5.33 / 15
Max. Delta Allocs op: 3.67 / 15

**Comment by fatihbaltaci** [comment]
Hi @nevzatseferoglu, thanks for your contribution. I was using ZSH and followed the instructions. It gave these errors: 

image

Do you know how I can fix that?

**Comment by ddosifyadmin** [comment]
Max. Delta Time op: 5.24 / 15
Max. Delta Alloc op: 5.53 / 15
Max. Delta Allocs op: 7.18 / 15

**Comment by nevzatseferoglu** [comment]
It seems that you also use `oh-my-zsh` in you zsh shell, I suppose that you followed setup guide according to it.

When I type `echo $fpath | tr ' ' '\n'`, I can see the auto-completion functions which are already set under the related oh-my-zsh plugin directory.
```
/Users/nevzatseferoglu/.oh-my-zsh/plugins/ddosify
/Users/nevzatseferoglu/.oh-my-zsh/plugins/fzf
/Users/nevzatseferoglu/.oh-my-zsh/plugins/docker
/Users/nevzatseferoglu/.oh-my-zsh/plugins/kubectl
```

For setting up `ddodify` specificially,  I put `ddosify` file into `/Users/nevzatseferoglu/.oh-my-zsh/plugins/`, then added `ddosify` literal under the `plugins=()` section of `.zshrc` file.

It seems that you don't have `zsh-autosuggestion`, since it is **not a dependency** for ddosify auto-suggestion, you can either omit it from the plugins section of `.zshrc` or install it from here  https://github.com/zsh-users/zsh-autosuggestions/blob/master/INSTALL.md. It basically stores history of commands options then suggests based on that history.

Since `zsh-autosuggestions` is not a dependency, I will send  another commit which fixes potential misunderstands in the guide. Thanks!

**Comment by ddosifyadmin** [comment]
Max. Delta Time op: 2.73 / 15
Max. Delta Alloc op: 4.19 / 15
Max. Delta Allocs op: 4.92 / 15

**Review by fatihbaltaci — APPROVED** [review]
@nevzatseferoglu thanks for your effort 🚀

**Comment by ddosifyadmin** [comment]
Max. Delta Time op: 0.00 / 15
Max. Delta Alloc op: 2.55 / 15
Max. Delta Allocs op: 3.10 / 15

**Pull request merged**
