### PR TITLE
Feature/os env vars in config

### PR DESCRIPTION
**Pull request by KshitijBharde**
### Type of Change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] This change requires a documentation update

### Description
Added support for using operating system environment variables in the config.json file using a specific format like {{$USER}}.

### Checklist
- [x] I have read the [CONTRIBUTING.md](../CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [x] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] I have updated the [README.md](../README.md) as necessary if there are changes.
- [x] I have tested the changes on my local machine before submitting the PR.

### CODE REVIEW

**Comment by ddosifyadmin** [comment]
Max. Delta Time op: 3.54 / 15
Max. Delta Alloc op: 0.90 / 15
Max. Delta Allocs op: 0.81 / 15

**Comment by kenanfarukcakir** [comment]
Hey, thank you for your contribution.
Could you please add some tests to raise the coverage to at least 80% ?
You can take a look at [codecov](https://app.codecov.io/gh/ddosify/ddosify/pull/165) for the pr.

**Comment by KshitijBharde** [comment]
@kenanfarukcakir Sure, will do

**Comment by ddosifyadmin** [comment]
Max. Delta Time op: 5.06 / 15
Max. Delta Alloc op: 2.72 / 15
Max. Delta Allocs op: 3.30 / 15

**Comment by fatihbaltaci** [comment]
Hey @KshitijBharde, thanks for your contribution. We appreciate it 🚀 I also thank @kenanfarukcakir for testing and reviewing ✅

**Pull request merged**
